[package]
name = "fs"
version = "0.1.0"
authors = ["Davis Wahl <daviswahl@gmail.com>"]

[dependencies]
libc = "0.2"
errno = "0.2.3"
error-chain = "0.11.0-rc.2"
serde = "1.0"
serde_derive = "1.0"
rmp-serde = "0.13"
typed-arena = "1.3"
